type: google.api.Service
config_version: 3
name: Notification System
title: Notification System
apis:
  - name: notification_sys.SimpleMessage
usage:
  rules:
  - selector: "*"
    allow_unregistered_calls: false
backend:
  rules:
    - selector: "*"
      address: <<gcp_project_name>> # Replace with your own value
      