type: google.api.Service
config_version: 3
name: <CLOUD_RUN_SERVICE_URL> # Replace with your own value
title: Notification System
apis:
  - name: notificationsys.SimpleMessage
usage:
  rules:
  - selector: "*"
    allow_unregistered_calls: true
backend:
  rules:
    - selector: "*"
      address: grpcs://<CLOUD_RUN_BACKEND_URL> # Replace with your own value      
